### ISSUE TITLE
How edit with custom editor?

### ISSUE THREAD

**Issue by FreeWebber** [flathub/org.filezillaproject.Filezilla#15]
Can't edit file with code editor! Even with `--filesystem=host`
`flatpak run --filesystem=host org.filezillaproject.Filezilla`
When connected to server -> RMB on file -> View/Edit
For editor i'm choose `/opt/sublime_text/sublime_text`
OS Linux Mint 19 (Ubuntu 18).

**Comment by nedrichards** [comment]
Yeah, fixing this issue is difficult, since this isn't how flatpak is designed to work (you're in a container, you're not supposed to see other things). There's work and thinking going on about better portals for this but fixing it isn't something we can do easily on an app level. The right place to have this sort of discussion would be https://github.com/flatpak/xdg-desktop-portal or https://github.com/flatpak/flatpak

**Comment by TingPing** [comment]
Transfer the file, edit it outside of filezilla, transfer it back.

**Comment by BassemN** [comment]
@TingPing this is very hard because sometimes I make frequent changes on many files on different paths so this will be a nightmare :)

**Comment by biswajit-paul** [comment]
Is there any update? I am getting this error on popup also:
~~~
ASSERT INFO:
./src/common/filefn.cpp(1610): assert "!szFile.empty()" failed in wxFindFileInPath(): empty file name in wxFindFileInPath

BACKTRACE:
(null)
~~~

I can not set VSCode as default editor which is located at /usr/share/code/code. It says location to found.

**Comment by baermathias** [comment]
#40 similar issue here.
I think there will be no solution in near future for the filezilla flatpak version. Either use the official AppImage or try the unofficial snap version.

**Comment by BassemN** [comment]
@baermathias Could you please send the AppImage link?

**Comment by baermathias** [comment]
https://filezilla-project.org/download.php?show_all=1

**Comment by BassemN** [comment]
@baermathias Thanks but the provided link doesn't contain AppImage
