### ISSUE TITLE
Fix missing icon in appstream.xml

### ISSUE THREAD

**Issue by rshuler** [flathub/org.filezillaproject.Filezilla#5]
The icon is not specified in the appstream.xml, and thus Filezilla no longer shows up in gnome-software.

It used to be fine, and I suspect the problem was introduced with this commit, when the appdata.xml was explicitly provided and thus precluded the old mechanism of copying the icon when generating the appstream:
426d8a00d6d8b7a77b5ade0b0eae12f2c3e7a52d

**Comment by TingPing** [comment]
The icon doesn't need to be specified in the appstream file, how it works is appstream loads the desktop file which references the icon name.

**Comment by rshuler** [comment]
Well, somehow the icon name is not ending up in the appstream.xml.gz file on the client, and thus the app does not show up in gnome-software.  Ditto for the category.  Perhaps there is a bug in the tooling on flathub, or perhaps the tooling requires the ID to end in ".desktop".  I just wrote a script to inspect the appstream.xml.gz, and a total of 5 apps have IDs not ending in ".desktop", and all 5 of these apps are missing icons and categories.  To be honest, I don't know if it is required or just convention that app IDs end in ".desktop", but I suspect that is part of the problem.  @nedrichards @ramcq Any thoughts?

**Comment by ramcq** [comment]
This looks like a bug in https://github.com/flatpak/flatpak/blob/master/common/flatpak-utils.c#L3862-L3871 where it assumes/requires that the app ID will end in .desktop, whereas this is not required by the spec: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic

IMO it's _super_ confusing/ambiguous of the spec to have used ".desktop" as a suffix here because it makes you think that it's something to do with the desktop filename - which is not the intention. Any similarity to actual files is purely coincidental. :)

**Comment by ramcq** [comment]
https://github.com/flatpak/flatpak/pull/1367

**Comment by ramcq** [comment]
(Thanks for digging Roddy. This would actually have afflicted the new Vim flatpak I just made too. :D)

**Comment by nedrichards** [comment]
@rshuler which are the other apps?

**Comment by TingPing** [comment]
- Marker's upstream appdata file
- OTPClient's upstream appdata file
- Zotero
