### ISSUE TITLE
Filezilla 3.60.2 not available on flathub

### ISSUE THREAD

**Issue by MikeNavy** [flathub/org.filezillaproject.Filezilla#83]
Hi,
Version 3.60.2 of Filezilla flatpak is not available on flathub, the available version is still 3.60.1. Update to 3.60.2 is not possible.

**Comment by MikeNavy** [comment]
No comment to this issue? Filezilla 3.60.2 update pull request has been merged on 22 July by nedrichards and closed, and the only available version at Flathub is the 3.60.1 (checked on 16 September).
Has the 3.60.2 version been removed, and why?
Is it a bug?
Regards,
MN

**Comment by joshuag1000** [comment]
Firstly I am not the maintainer of this flathub app.

But if you look at the buildbot here: https://buildbot.flathub.org/#/builders/32/builds/101796

The build that was run on flathub failed because of an invalid appdata file. This would not have been caught on a local build which is probably why the app is still on 3.60.1.
It appears that this was missed by the maintainer and so nothing was done.
You can also see that the builds failed here:
![image](https://user-images.githubusercontent.com/28513051/193361436-2042e97a-3f3c-4329-8d05-73976ff4ebf7.png)

This will however not be an issue once the app is updated to version 3.61.0 (hopefully when my merge request is merged #84)

**Comment by nedrichards** [comment]
This should be fixed by https://github.com/flathub/org.filezillaproject.Filezilla/commit/e68456ce96e5691f515ff6e9cbf872cb07ebac27
